# Hexo优化配置

# 代码压缩
minify:
  html:
    enable: true
    exclude: []
  css:
    enable: true
    exclude: []
  js:
    enable: true
    exclude: []

# 图片懒加载
lazyload:
  enable: true
  onlypost: false
  loadingImg: /img/loading.gif

# 缓存
cache:
  enable: true
  ttl: 604800 # 7天
